### ISSUE TITLE
Problem with parsing demo

### ISSUE THREAD

**Issue by DrugsMaster** [BeepFelix/CSGO-Overwatch-Bot#1]
Hello, I got this message, can you help me?

```
Logged in
--------------------
Requested Overwatch case
Downloading case 3320124219341144198 from url http://replay185.valve.net/730/003320051069605642626_0143849426.dem.bz2
Finished downloading 3320124219341144198, unpacking...
Finished unpacking 3320124219341144198, parsing as suspect 76561198881764615...
{ error: Error: Cannot get 32 bit(s) from offset 25992, 0 available
    at BitView.getBits (/usr/share/CSGO-Overwatch-Bot/node_modules/bit-buffer/bit-buffer.js:58:9)
    at BitView.bit_buffer_1.BitView.getBits (/usr/share/CSGO-Overwatch-Bot/node_modules/demofile/dist/ext/bitbuffer.js:33:28)
    at BitStream.readBits (/usr/share/CSGO-Overwatch-Bot/node_modules/bit-buffer/bit-buffer.js:273:23)
    at BitStream.bit_buffer_1.BitStream.readUBits (/usr/share/CSGO-Overwatch-Bot/node_modules/demofile/dist/ext/bitbuffer.js:51:17)
    at Object.bitbuf [as decode] (/usr/share/CSGO-Overwatch-Bot/node_modules/demofile/dist/props.js:81:41)
    at Entities._parseEntityUpdate (/usr/share/CSGO-Overwatch-Bot/node_modules/demofile/dist/entities.js:338:38)
    at Entities._parseInstanceBaseline (/usr/share/CSGO-Overwatch-Bot/node_modules/demofile/dist/entities.js:436:31)
    at Entities.handleDataTables (/usr/share/CSGO-Overwatch-Bot/node_modules/demofile/dist/entities.js:205:56)
    at DemoFile._handleDataTables (/usr/share/CSGO-Overwatch-Bot/node_modules/demofile/dist/demo.js:178:23)
    at DemoFile._parseRecurse (/usr/share/CSGO-Overwatch-Bot/node_modules/demofile/dist/demo.js:217:26) }
Done parsing case 3320124219341144198
/usr/share/CSGO-Overwatch-Bot/node_modules/demofile/dist/demo.js:250
                throw e;
                ^

Error: Cannot get 32 bit(s) from offset 25992, 0 available
    at BitView.getBits (/usr/share/CSGO-Overwatch-Bot/node_modules/bit-buffer/bit-buffer.js:58:9)
    at BitView.bit_buffer_1.BitView.getBits (/usr/share/CSGO-Overwatch-Bot/node_modules/demofile/dist/ext/bitbuffer.js:33:28)
    at BitStream.readBits (/usr/share/CSGO-Overwatch-Bot/node_modules/bit-buffer/bit-buffer.js:273:23)
    at BitStream.bit_buffer_1.BitStream.readUBits (/usr/share/CSGO-Overwatch-Bot/node_modules/demofile/dist/ext/bitbuffer.js:51:17)
    at Object.bitbuf [as decode] (/usr/share/CSGO-Overwatch-Bot/node_modules/demofile/dist/props.js:81:41)
    at Entities._parseEntityUpdate (/usr/share/CSGO-Overwatch-Bot/node_modules/demofile/dist/entities.js:338:38)
    at Entities._parseInstanceBaseline (/usr/share/CSGO-Overwatch-Bot/node_modules/demofile/dist/entities.js:436:31)
    at Entities.handleDataTables (/usr/share/CSGO-Overwatch-Bot/node_modules/demofile/dist/entities.js:205:56)
    at DemoFile._handleDataTables (/usr/share/CSGO-Overwatch-Bot/node_modules/demofile/dist/demo.js:178:23)
    at DemoFile._parseRecurse (/usr/share/CSGO-Overwatch-Bot/node_modules/demofile/dist/demo.js:217:26)

```

**Comment by BeepFelix** [comment]
This is due to the [demofile](https://github.com/saul/demofile) module which I use in this code. Wait until [this issue](https://github.com/saul/demofile/issues/95) is resolved.
